version: "3.0"
services:
    db:
        image: mariadb:10.3
        restart: 'always'
        volumes:
            - ${PWD}/mariadb:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: koha
            MYSQL_USER: koha
            MYSQL_PASSWORD: koha

    memcached:
        image: memcached:alpine
        restart: 'always'

    elasticsearch:
        image: koha/elasticsearch-icu
        restart: 'always'
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
    web:
        image: awenmedia/koha:latest
        restart: 'always'
        env_file:
            - .env
        volumes:
            - ${PWD}/koha:/home/koha/koha
        ports:
            - 8080:5000
            - 80:5001
        depends_on:
            - db
            - memcached
            - elasticsearch
