version: "3.0"
services:
    db:
        image: mariadb:10.2
        restart: 'always'
        volumes:
            - ${PWD}/datadb:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: koha_awen
            MYSQL_USER: koha
            MYSQL_PASSWORD: koha

    memcached:
        image: memcached:alpine
        restart: 'always'

    elasticsearch:
        image: koha/elasticsearch-icu
        restart: 'always'
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
